In [2]:
import numpy as np

In [3]:
type(np.ones(5))

numpy.ndarray

In [6]:
lista = [10,20,30,20,50]
print(type(lista))
arr = np.array([10,20,30,20,50])
print(arr)
print(type(arr))

<class 'list'>
[10 20 30 20 50]
<class 'numpy.ndarray'>


In [16]:
#1D
arro0D = np.array([1,2,3,4])

#2D
arr2d = np.array([[1,2,3], [4,5,6]])
print(arr2d)

#3D
arr3d = np.array ([
                  [[1,2,3], [4,5,6]], 
                  [[10,20,30], [40,50,60]]
                  ])
print(Arr3d)

[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [17]:
arr3d.ndim

3

In [48]:
arr = np.array([10, 20, 30, 40, 50, 60, 70], ndmin=2)
print(arr[0])
print(arr[0,-1])
print(arr[0,2:4])

[10 20 30 40 50 60 70]
70
[30 40]


In [50]:
arr = np.array([1,2,3])
arr + 1 #esta operacion esta vectorizada


array([2, 3, 4])

In [26]:
arr = np.array([
                [10,20,30,40,50],
                [60,70,80,90,100]
                ])

#si solo le paso un num como indice a la matriz
#me quedo con la fila entera de esa serie
arr[0,1]

arr[1, :]
#para sacar las columnas
arr[: , 3]
#se pueden usar indices negativos
arr[1 , -1]

np.int64(100)

In [17]:
arr = np.array([10,20,30,40,50,60,70,80])

print(arr[1:5])
print(arr[1:6:2])
print(arr[:4:2]) #empiexa en el cero y salta de dos en dos 
print(arr[0:3:2]) #desde la 0 a la 3 y se salta 2

[20 30 40 50]
[20 40 60]
[10 30]
[10 30]


In [21]:
np.zeros(10) #inicio decimales y por defecto es un float 
np.empty(5) #nos da numeros aleatorios 
np.arange(6) #igual que el range 

array([0, 1, 2, 3, 4, 5])

In [27]:
a1 = np.ones(3)
a2 = np.zeros(3)
np.array(list(a1) + list(a2))


array([1., 1., 1., 0., 0., 0.])

In [29]:
l1 = [1,2,3]
l2 = [4,5,6]
print(l1 +l2)
print(a1 + a2)

[1, 2, 3, 4, 5, 6]
[1. 1. 1.]


In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
x =np.hstack((arr1,arr2))
x.shape

(6,)

In [6]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5])
x =np.hstack((arr1,arr2))
x.shape

(5,)

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6]) #tiene que tener la misma dimension
x =np.vstack((arr1,arr2)) 
x.shape

(2, 3)

In [11]:
arr1 = np.array([1,2,3], [4,5,6])
arr2 = np.array([7,8,9]) #tiene que tener la misma dimension
x =np.hstack((arr1,arr2)) 
x

TypeError: Field elements must be 2- or 3-tuples, got '4'

## Ejercicios (1)

>1. Almacena en la variable `arr` un array con 10 ceros, 10 unos y 10 cuatros. Luego imprime el array y su número de elementos por pantalla.

In [40]:
a1 = np.ones(10)
a2 = np.zeros(10)
a3 = np.full(10,4)
print(a3)

arr3d = np.array ([
                  a1, a2,a3
                  ])
print(arr3d)

[4 4 4 4 4 4 4 4 4 4]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]


>2. Crea variable numeros enteros del 20 al 50.

In [44]:
arr = np.arange(20,51)
print(arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50]


>3. Crea la variable `arr` con los números pares del 20 al 50 e imprímela por pantalla.

In [51]:
n = 2
arr = np.arange(20, 50 + n, n, dtype=int)
print(arr)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


>4. Crea la variable `arr` con los números enteros del 20 al 50 que sean múltiplo de 5 e imprímela por pantalla.

In [4]:
arr = np.arange(20, 50+2, 5, dtype=int)
print(arr)

[20 25 30 35 40 45 50]


>5. Crea la variable `arr` con 10 números aleatorios.

In [13]:
rng = np.random.default_rng(seed=2024)
arr = rng.random(10)
print(arr)

[0.67583134 0.2143232  0.30945203 0.7994661  0.9958021  0.14223182
 0.07872553 0.18082381 0.35964689 0.16961925]


>6. Crea e imprime la variable `arr`, que será una matriz de 3x3 cuyos elementos son todos 1.


In [11]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


>7. Crea e imprime una variable `arr` que con la dimensión 3x5x4 que contenga números aleatorios.

In [12]:
#arr = rng.random((4,5,3)) #puedo poner todos los argumentos que quiera (2,1,2,4,5)
#print(arr)

arr = np.random.rand(3,4,5)
arr

array([[[0.23331339, 0.11290162, 0.04139873, 0.3665868 , 0.48340404],
        [0.70812826, 0.24534534, 0.85279916, 0.92788402, 0.04430483],
        [0.69091091, 0.51097931, 0.15333741, 0.23183212, 0.83238511],
        [0.19448769, 0.57355024, 0.03411105, 0.96393996, 0.84333418]],

       [[0.41414072, 0.17787092, 0.56025422, 0.47179161, 0.0525395 ],
        [0.90067344, 0.58577287, 0.4881865 , 0.06279265, 0.64778913],
        [0.54586767, 0.02969225, 0.30882527, 0.16041681, 0.56720833],
        [0.16077505, 0.56768572, 0.89641437, 0.38070131, 0.85269338]],

       [[0.65925844, 0.16613737, 0.22053969, 0.8781794 , 0.06390329],
        [0.46487807, 0.99048859, 0.85180543, 0.31986811, 0.75406848],
        [0.627584  , 0.15426867, 0.80876959, 0.54964344, 0.73688917],
        [0.82154522, 0.09700771, 0.71424164, 0.50520961, 0.88481385]]])

>8. Crea (automáticamente) e imprime una variable `arr` que contenga:

In [14]:
arr = np.arange(0, 1000, 10).reshape(10,10)
arr 

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140, 150, 160, 170, 180, 190],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340, 350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490],
       [500, 510, 520, 530, 540, 550, 560, 570, 580, 590],
       [600, 610, 620, 630, 640, 650, 660, 670, 680, 690],
       [700, 710, 720, 730, 740, 750, 760, 770, 780, 790],
       [800, 810, 820, 830, 840, 850, 860, 870, 880, 890],
       [900, 910, 920, 930, 940, 950, 960, 970, 980, 990]])

>9. Crea e imprime la variable `arr`, que contendrá una matriz de dimensión 10x10 donde todos sus elementos son 0 a excepción de los bordes, que contendrán un 1.

In [47]:
arr = np.zeros((10,10))
values = np.ones((1,10,2)) #formato columnas
new_arr = np.insert(arr,[0,10],values, axis=1)
print(new_arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


>10. Crea e imprime la variable `arr`, que será una matriz de 5x5 cuyos elementos de la diagonal son los valores del 1 al 5 y el resto 0.

In [82]:
arr = np.eye(5,5)
arr[:,1] = arr[1,:] *2
arr[:,2] = arr[2,:] *3
arr[:,3] = arr[3,:] *4
arr[:,4] = arr[4,:] *5
print(arr)

#mas automatizado
n = range(0,5)
for i in n:
    arr = np.eye(5,5)
    resultado = arr[:,i] = arr[i,:] * (i+1)
    print(resultado)


[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]
[1. 0. 0. 0. 0.]
[0. 2. 0. 0. 0.]
[0. 0. 3. 0. 0.]
[0. 0. 0. 4. 0.]
[0. 0. 0. 0. 5.]


In [85]:
#mas sencillo
x = [1,2,3,4,5]
arr = np.diag(x)
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

>11. Crea e imprime la variable `arr`, que será inicalmente una matriz de 3x1 de todo unos y añádele luego una columna adicional de ceros.

In [91]:
arr = np.ones((3,1))
values = np.zeros((1,3)) #formato columnas
new_arr = np.insert(arr,1,values, axis=1)
new_arr

array([[1., 0.],
       [1., 0.],
       [1., 0.]])

>12. Crea e imprime una variable `arr` que contenga:
```
array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [101, 111, 121, 131, 141, 151, 161, 171, 181, 191],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [301, 311, 321, 331, 341, 351, 361, 371, 381, 391],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490],
       [501, 511, 521, 531, 541, 551, 561, 571, 581, 591],
       [600, 610, 620, 630, 640, 650, 660, 670, 680, 690],
       [701, 711, 721, 731, 741, 751, 761, 771, 781, 791],
       [800, 810, 820, 830, 840, 850, 860, 870, 880, 890],
       [901, 911, 921, 931, 941, 951, 961, 971, 981, 991]])
```

In [124]:
arr = np.arange(0,1000, 10).reshape((10,10))
arr[1,:] = arr[1,:] + 1
arr[3,:] = arr[3,:] + 1
arr[5,:] = arr[5,:] + 1
arr[7,:] = arr[7,:] + 1
arr[9,:] = arr[9,:] + 1
arr[:,0]

array([  0, 101, 200, 301, 400, 501, 600, 701, 800, 901])

>13. Crea el array:
```
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
 ```
 y muestra para cada elemento el mensaje `El elemento en la fila .. y columna .. es ..`

In [171]:
#no me convence este metodo...
arr = np.arange(10,22, 1).reshape(4,3)
it =  np.nditer(arr, flags=['multi_index'])
while not it.finished:
    fila = it.multi_index[0]      
    columna = it.multi_index[1]   
    print("El valor %d está en la fila %d y en la columna %d" % (it[0], fila, columna), end='\n')
    is_not_finished = it.iternext()

El valor 10 está en la fila 0 y en la columna 0
El valor 11 está en la fila 0 y en la columna 1
El valor 12 está en la fila 0 y en la columna 2
El valor 13 está en la fila 1 y en la columna 0
El valor 14 está en la fila 1 y en la columna 1
El valor 15 está en la fila 1 y en la columna 2
El valor 16 está en la fila 2 y en la columna 0
El valor 17 está en la fila 2 y en la columna 1
El valor 18 está en la fila 2 y en la columna 2
El valor 19 está en la fila 3 y en la columna 0
El valor 20 está en la fila 3 y en la columna 1
El valor 21 está en la fila 3 y en la columna 2


>14. Crea un array con los valores del 0 al 20, ambos incluídos, y cambia el signo de los números del 7 al 12 (ambos incluídos).

In [8]:
arr = np.arange(0,21)
arr[7:13:1] = arr[7:13:1] *-1 #tengo que ponerlo a la izquierda y derecha para que no lo sobre-escriba
arr

array([  0,   1,   2,   3,   4,   5,   6,  -7,  -8,  -9, -10, -11, -12,
        13,  14,  15,  16,  17,  18,  19,  20])

>15. Escribe un trozo de código que termine imprimiendo uno de los posibles mensajes _No hay ceros/Hay ceros_ en función del valor de la variable `no_hay_ceros`, que será `True` en caso de que en el array almacenado en `arr` no hay ningún cero.

In [26]:
a = np.array([0, 2, 3, 4, 5, 6, 7])
arr = np.any(a = 0)
if arr == True:
    print('No hay ceros')
else:
    print('Hay ceros')

Hay ceros


>16. Asumiendo que todos los valores del array almacenado en `arr` son numéricos, escribe un trozo de código que imprima _Todos positivos_ en caso de que todos sean mayor que cero y _No todos positivos_ en caso contrario.

In [35]:
a = np.array([0, 2, -3, 4, 5, 6, 7])
arr = np.all(a > 0)
if arr == True:
  print("Todos positivos")
else:
    print("No todos son positivos")

No todos positivos


>17. Escribe un trozo de código que imprima _Aceptado_ si la diferencia entre cada par de elementos de los arrays `x` e `y` es siempre menor o igual que 5 y _Rechazado_ en caso contrario.

In [42]:
a= np.arange(0,50,4)
arr = np.diff(a) 
if np.any(arr > 5):
    print("Aceptado")
else:
    print('Rechazado')

Rechazado


>18. Escribe un trozo de código que imprima `Falta información` si alguno de los elementos del array `arr` tiene un valor NaN y `Todo correcto` en caso contrario.

In [45]:
a = np.array([0, 2, np.nan, 4, 5, 6, 7])
arr = np.isnan(a)
if np.any(arr) == True:
    print('Falta informacion')
else:
    print('Todo correcto')

Falta informacion


>19. Imprime el mensaje _El resultado es: ..._ tras multiplicar elemento a elemento los vectores `x` e `y` y hacer la suma de los resultados.

In [54]:
arr= np.arange(1,4,1) #si empiezo en 0 sale 0
arr
resultado = np.prod(arr)
print(resultado)

6


>20. Comprueba si los arrays `x` e `y` son iguales elemento a elemento

In [59]:
arr1 = ([1,2,3])
arr2 = ([1,2,3], [1,2,3])

np.array_equiv(arr1,arr2) #True porque son los mismos elementos
np.array_equal(arr1,arr2) #False porque no tienen la misma dimension 

False