In [3]:
import numpy as np

In [3]:
type(np.ones(5))

numpy.ndarray

In [6]:
lista = [10,20,30,20,50]
print(type(lista))
arr = np.array([10,20,30,20,50])
print(arr)
print(type(arr))

<class 'list'>
[10 20 30 20 50]
<class 'numpy.ndarray'>


In [16]:
#1D
arro0D = np.array([1,2,3,4])

#2D
arr2d = np.array([[1,2,3], [4,5,6]])
print(arr2d)

#3D
arr3d = np.array ([
                  [[1,2,3], [4,5,6]], 
                  [[10,20,30], [40,50,60]]
                  ])
print(Arr3d)

[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


In [17]:
arr3d.ndim

3

In [48]:
arr = np.array([10, 20, 30, 40, 50, 60, 70], ndmin=2)
print(arr[0])
print(arr[0,-1])
print(arr[0,2:4])

[10 20 30 40 50 60 70]
70
[30 40]


In [50]:
arr = np.array([1,2,3])
arr + 1 #esta operacion esta vectorizada


array([2, 3, 4])

In [26]:
arr = np.array([
                [10,20,30,40,50],
                [60,70,80,90,100]
                ])

#si solo le paso un num como indice a la matriz
#me quedo con la fila entera de esa serie
arr[0,1]

arr[1, :]
#para sacar las columnas
arr[: , 3]
#se pueden usar indices negativos
arr[1 , -1]

np.int64(100)

In [17]:
arr = np.array([10,20,30,40,50,60,70,80])

print(arr[1:5])
print(arr[1:6:2])
print(arr[:4:2]) #empiexa en el cero y salta de dos en dos 
print(arr[0:3:2]) #desde la 0 a la 3 y se salta 2

[20 30 40 50]
[20 40 60]
[10 30]
[10 30]


In [21]:
np.zeros(10) #inicio decimales y por defecto es un float 
np.empty(5) #nos da numeros aleatorios 
np.arange(6) #igual que el range 

array([0, 1, 2, 3, 4, 5])

In [27]:
a1 = np.ones(3)
a2 = np.zeros(3)
np.array(list(a1) + list(a2))


array([1., 1., 1., 0., 0., 0.])

In [29]:
l1 = [1,2,3]
l2 = [4,5,6]
print(l1 +l2)
print(a1 + a2)

[1, 2, 3, 4, 5, 6]
[1. 1. 1.]


>1. Almacena en la variable `arr` un array con 10 ceros, 10 unos y 10 cuatros. Luego imprime el array y su número de elementos por pantalla.

In [40]:
a1 = np.ones(10)
a2 = np.zeros(10)
a3 = np.full(10,4)
print(a3)

arr3d = np.array ([
                  a1, a2,a3
                  ])
print(arr3d)

[4 4 4 4 4 4 4 4 4 4]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]


>2. Crea variable numeros enteros del 20 al 50.

In [44]:
arr = np.arange(20,51)
print(arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50]


>3. Crea la variable `arr` con los números pares del 20 al 50 e imprímela por pantalla.

In [51]:
n = 2
arr = np.arange(20, 50 + n, n, dtype=int)
print(arr)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


>4. Crea la variable `arr` con los números enteros del 20 al 50 que sean múltiplo de 5 e imprímela por pantalla.

In [4]:
arr = np.arange(20, 50+2, 5, dtype=int)
print(arr)

[20 25 30 35 40 45 50]


>5. Crea la variable `arr` con 10 números aleatorios.

In [13]:
rng = np.random.default_rng(seed=2024)
arr = rng.random(10)
print(arr)

[0.67583134 0.2143232  0.30945203 0.7994661  0.9958021  0.14223182
 0.07872553 0.18082381 0.35964689 0.16961925]


>6. Crea e imprime la variable `arr`, que será una matriz de 3x3 cuyos elementos son todos 1.


In [11]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


>7. Crea e imprime una variable `arr` que con la dimensión 3x5x4 que contenga números aleatorios.

In [21]:
arr = rng.random((4,5,3)) #puedo poner todos los argumentos que quiera (2,1,2,4,5)
print(arr)

[[[0.45261099 0.74477338 0.34895141]
  [0.62780661 0.34585771 0.07311693]
  [0.12293647 0.01774725 0.03864987]
  [0.68916698 0.19837232 0.86383024]
  [0.7687165  0.73594069 0.66807598]]

 [[0.92725658 0.54566953 0.27308837]
  [0.70281288 0.13180528 0.29975193]
  [0.01560048 0.96061722 0.29334406]
  [0.85706893 0.89476375 0.50428108]
  [0.74964087 0.31133147 0.40892744]]

 [[0.90597347 0.95920545 0.08697646]
  [0.81366327 0.796418   0.42604348]
  [0.02556243 0.4582288  0.65186925]
  [0.14557361 0.56573143 0.90727299]
  [0.14600425 0.68338435 0.39047656]]

 [[0.76915327 0.61262005 0.40835005]
  [0.49513094 0.06718195 0.74929088]
  [0.32637492 0.96669323 0.88002796]
  [0.12679135 0.96925614 0.36718528]
  [0.70802111 0.91773567 0.20967025]]]


>8. Crea (automáticamente) e imprime una variable `arr` que contenga:

In [27]:
arr = np.arange(0, 1000, 10).reshape(10,10)

SyntaxError: invalid syntax (1040110401.py, line 2)

>9. Crea e imprime la variable `arr`, que contendrá una matriz de dimensión 10x10 donde todos sus elementos son 0 a excepción de los bordes, que contendrán un 1.

In [47]:
arr = np.zeros((10,10))
values = np.ones((1,10,2)) #formato columnas
new_arr = np.insert(arr,[0,10],values, axis=1)
print(new_arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


>10. Crea e imprime la variable `arr`, que será una matriz de 5x5 cuyos elementos de la diagonal son los valores del 1 al 5 y el resto 0.

In [82]:
arr = np.eye(5,5)
arr[:,1] = arr[1,:] *2
arr[:,2] = arr[2,:] *3
arr[:,3] = arr[3,:] *4
arr[:,4] = arr[4,:] *5
print(arr)

#mas automatizado
n = range(0,5)
for i in n:
    arr = np.eye(5,5)
    resultado = arr[:,i] = arr[i,:] * (i+1)
    print(resultado)


[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]
[1. 0. 0. 0. 0.]
[0. 2. 0. 0. 0.]
[0. 0. 3. 0. 0.]
[0. 0. 0. 4. 0.]
[0. 0. 0. 0. 5.]


In [85]:
#mas sencillo
x = [1,2,3,4,5]
arr = np.diag(x)
arr

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

>11. Crea e imprime la variable `arr`, que será inicalmente una matriz de 3x1 de todo unos y añádele luego una columna adicional de ceros.

In [91]:
arr = np.ones((3,1))
values = np.zeros((1,3)) #formato columnas
new_arr = np.insert(arr,1,values, axis=1)
new_arr

array([[1., 0.],
       [1., 0.],
       [1., 0.]])

>12. Crea e imprime una variable `arr` que contenga:
```
array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90],
       [101, 111, 121, 131, 141, 151, 161, 171, 181, 191],
       [200, 210, 220, 230, 240, 250, 260, 270, 280, 290],
       [301, 311, 321, 331, 341, 351, 361, 371, 381, 391],
       [400, 410, 420, 430, 440, 450, 460, 470, 480, 490],
       [501, 511, 521, 531, 541, 551, 561, 571, 581, 591],
       [600, 610, 620, 630, 640, 650, 660, 670, 680, 690],
       [701, 711, 721, 731, 741, 751, 761, 771, 781, 791],
       [800, 810, 820, 830, 840, 850, 860, 870, 880, 890],
       [901, 911, 921, 931, 941, 951, 961, 971, 981, 991]])
```

In [124]:
arr = np.arange(0,1000, 10).reshape((10,10))
arr[1,:] = arr[1,:] + 1
arr[3,:] = arr[3,:] + 1
arr[5,:] = arr[5,:] + 1
arr[7,:] = arr[7,:] + 1
arr[9,:] = arr[9,:] + 1
arr[:,0]

array([  0, 101, 200, 301, 400, 501, 600, 701, 800, 901])

>13. Crea el array:
```
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
 ```
 y muedsta para cada elemento el mensaje `El elemento en la fila .. y columna .. es ..`

In [171]:
#no me convence este metodo...
arr = np.arange(10,22, 1).reshape(4,3)
it =  np.nditer(arr, flags=['multi_index'])
while not it.finished:
    fila = it.multi_index[0]      
    columna = it.multi_index[1]   
    print("El valor %d está en la fila %d y en la columna %d" % (it[0], fila, columna), end='\n')
    is_not_finished = it.iternext()



El valor 10 está en la fila 0 y en la columna 0
El valor 11 está en la fila 0 y en la columna 1
El valor 12 está en la fila 0 y en la columna 2
El valor 13 está en la fila 1 y en la columna 0
El valor 14 está en la fila 1 y en la columna 1
El valor 15 está en la fila 1 y en la columna 2
El valor 16 está en la fila 2 y en la columna 0
El valor 17 está en la fila 2 y en la columna 1
El valor 18 está en la fila 2 y en la columna 2
El valor 19 está en la fila 3 y en la columna 0
El valor 20 está en la fila 3 y en la columna 1
El valor 21 está en la fila 3 y en la columna 2


14. Crea un array con los valores del 0 al 20, ambos incluídos, y cambia el signo de los números del 7 al 12 (ambos incluídos).
15. Escribe un trozo de código que termine imprimiendo uno de los posibles mensajes _No hay ceros/Hay ceros_ en función del valor de la variable `no_hay_ceros`, que será `True` en caso de que en el array almacenado en `arr` no hay ningún cero.
16. Asuminedo que todos los valores del array almacenado en `arr` son numéricos, escribe un trozo de código que imprima _Todos positivos_ en caso de que todos sean mayor que cero y _No todos positivos_ en caso contrario.
17. Escribe un trozo de código que imprima _Aceptado_ si la diferencia entre cada par de elementos de los arrays `x` e `y` es siempre menor o igual que 5 y _Rechazado_ en caso contrario.
18. Escribe un trozo de código que imprima `Falta información` si alguno de los elementos del array `arr` tiene un valor NaN y `Todo correcto` en caso contrario.
19. Imprime el mensaje _El resultado es: ..._ tras multiplicar elemento a elemento los vectores `x` e `y` y hacer la suma de los resultados.
20. Comprueba si los arrays `x` e `y` son iguales elemento a elemento